=== jocnud/nucleus8583/nucleus8583-core/src/main/resources/META-INF/nucleus8583/nucleus8583.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.nucleus8583.org/schema/nucleus8583"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.nucleus8583.org/schema/nucleus8583"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:simpleType name="alignment">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="left" />
            <xsd:enumeration value="l" />

            <xsd:enumeration value="right" />
            <xsd:enumeration value="r" />

            <xsd:enumeration value="none" />
            <xsd:enumeration value="n" />

            <xsd:enumeration value="uleft" />
            <xsd:enumeration value="ul" />

            <xsd:enumeration value="uright" />
            <xsd:enumeration value="ur" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="field-no">
        <xsd:restriction base="xsd:unsignedInt">
            <xsd:minInclusive value="0" />
            <xsd:maxInclusive value="192" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="field">
        <xsd:attribute name="no" type="field-no" use="required" />
        <xsd:attribute name="type" type="xsd:string" use="required" />

        <xsd:attribute name="description" type="xsd:string" use="optional" default="" />

        <xsd:attribute name="length" type="length" use="optional" />

        <xsd:attribute name="alignment" type="alignment" use="optional" />
        <xsd:attribute name="padWith" type="xsd:string" use="optional" />

        <xsd:attribute name="emptyValue" type="xsd:string" use="optional" />
    
        <xsd:attribute name="maxLength" type="length" use="optional" />
        
        <xsd:attribute name="subMessage-ref" type="xsd:string" use="optional" />
    </xsd:complexType>

    <xsd:complexType name="type">
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="class" type="xsd:string" use="required" />

        <xsd:attribute name="description" type="xsd:string" use="optional" default="" />

        <xsd:attribute name="alignment" type="alignment" use="optional" />
        <xsd:attribute name="padWith" type="xsd:string" use="optional" />

        <xsd:attribute name="emptyValue" type="xsd:string" use="optional" />

        <xsd:attribute name="prefixLength" type="prefixLength" use="optional" />
        <xsd:attribute name="maxLength" type="length" use="optional" />
    </xsd:complexType>

    <xsd:complexType name="message">
        <xsd:sequence>
            <xsd:element name="field" type="field" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>

        <xsd:attribute name="name" use="optional" type="xsd:string" />
        <xsd:attribute name="description" use="optional" type="xsd:string" default="" />
    </xsd:complexType>

    <xsd:complexType name="import">
        <xsd:attribute name="url" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:element name="nucleus8583">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <xsd:element name="type" type="type" />
                    <xsd:element name="message" type="message" />
                    <xsd:element name="import" type="import" />
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:simpleType name="length">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1" />
            <xsd:maxExclusive value="1000000000" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="prefixLength">
        <xsd:restriction base="xsd:int">
            <xsd:minInclusive value="1" />
            <xsd:maxExclusive value="9" />
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== jocnud/nucleus8583/nucleus8583-core/src/test/resources/META-INF/codec8583-no28.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<nucleus8583 xmlns="http://www.nucleus8583.org/schema/nucleus8583"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.nucleus8583.org/schema/nucleus8583 
                                 http://www.nucleus8583.org/schema/nucleus8583.xsd">

    <import url="classpath:META-INF/nucleus8583/nucleus8583-types.xml" />
    
	<message>
	    <field no="0" type="n" length="4"/>
	    <field no="1" type="bitmap" />
	    <field no="2" type="n .." maxLength="16"/>
	    <field no="3" type="n" length="6"/>
	    <field no="4" type="n" length="12"/>
	    <field no="5" type="n" length="12"/>
	    <field no="6" type="n" length="12"/>
	    <field no="7" type="n" length="10"/>
	    <field no="8" type="n" length="8"/>
	    <field no="9" type="n" length="8"/>
	    <field no="10" type="n" length="8"/>
	    <field no="11" type="n" length="6"/>
	    <field no="12" type="n" length="6"/>
	    <field no="13" type="n" length="4"/>
	    <field no="14" type="n" length="4"/>
	    <field no="15" type="n" length="4"/>
	    <field no="16" type="n" length="4"/>
	    <field no="17" type="n" length="4"/>
	    <field no="18" type="n" length="4"/>
	    <field no="19" type="n" length="3"/>
	    <field no="20" type="n" length="3"/>
	    <field no="21" type="n" length="3"/>
	    <field no="22" type="n" length="3"/>
	    <field no="23" type="n" length="3"/>
	    <field no="24" type="n" length="3"/>
	    <field no="25" type="n" length="2"/>
	    <field no="26" type="n" length="2"/>
	    <field no="27" type="n" length="1"/>
	    <field no="29" type="s" length="9"/>
	    <field no="32" type="n .." maxLength="11"/>
	    <field no="33" type="n .." maxLength="11"/>
	    <field no="34" type="ans .." maxLength="28"/>
	    <field no="35" type="n .." maxLength="37"/>
	    <field no="36" type="ans ..." maxLength="104"/>
	    <field no="37" type="s" length="12"/>
	    <field no="38" type="s" length="6"/>
	    <field no="39" type="s" length="2"/>
	    <field no="40" type="s" length="3"/>
	    <field no="41" type="s" length="8"/>
	    <field no="42" type="s" length="15"/>
	    <field no="43" type="s" length="40"/>
	    <field no="44" type="ans .." maxLength="25"/>
	    <field no="45" type="ans .." maxLength="76"/>
	    <field no="46" type="ans ..." maxLength="999"/>
	    <field no="47" type="ans ..." maxLength="999"/>
	    <field no="48" type="ans ..." maxLength="999"/>
	    <field no="49" type="s" length="3"/>
	    <field no="50" type="s" length="3"/>
	    <field no="51" type="s" length="3"/>
	    <field no="52" type="n" length="16"/>
	    <field no="53" type="n" length="16"/>
	    <field no="54" type="ans ..." maxLength="120"/>
	    <field no="55" type="ans ..." maxLength="999"/>
	    <field no="56" type="ans ..." maxLength="999"/>
	    <field no="57" type="ans ..." maxLength="999"/>
	    <field no="58" type="ans ..." maxLength="999"/>
	    <field no="59" type="ans ..." maxLength="999"/>
	    <field no="60" type="ans ..." maxLength="999"/>
	    <field no="61" type="ans ..." maxLength="999"/>
	    <field no="62" type="ans ..." maxLength="999"/>
	    <field no="63" type="ans ..." maxLength="999"/>
	    <field no="64" type="b" length="8"/>
	    <field no="65" type="bitmap" />
	    <field no="66" type="n" length="1"/>
	    <field no="67" type="n" length="2"/>
	    <field no="68" type="n" length="3"/>
	    <field no="69" type="n" length="3"/>
	    <field no="70" type="n" length="3"/>
	    <field no="71" type="n" length="4"/>
	    <field no="72" type="n" length="4"/>
	    <field no="73" type="n" length="6"/>
	    <field no="74" type="n" length="10"/>
	    <field no="75" type="n" length="10"/>
	    <field no="76" type="n" length="10"/>
	    <field no="77" type="n" length="10"/>
	    <field no="78" type="n" length="10"/>
	    <field no="79" type="n" length="10"/>
	    <field no="80" type="n" length="10"/>
	    <field no="81" type="n" length="10"/>
	    <field no="82" type="n" length="12"/>
	    <field no="83" type="n" length="12"/>
	    <field no="84" type="n" length="12"/>
	    <field no="85" type="n" length="12"/>
	    <field no="86" type="n" length="16"/>
	    <field no="87" type="n" length="16"/>
	    <field no="88" type="n" length="16"/>
	    <field no="89" type="n" length="16"/>
	    <field no="90" type="n" length="42"/>
	    <field no="91" type="s" length="1"/>
	    <field no="92" type="s" length="2"/>
	    <field no="93" type="s" length="6"/>
	    <field no="94" type="s" length="7"/>
	    <field no="95" type="s" length="42"/>
	    <field no="96" type="b" length="16"/>
	    <field no="98" type="s" length="25"/>
	    <field no="99" type="n .." maxLength="11"/>
	    <field no="100" type="n .." maxLength="11"/>
	    <field no="101" type="ans .." maxLength="17"/>
	    <field no="102" type="ans .." maxLength="13"/>
	    <field no="103" type="ans .." maxLength="10"/>
	    <field no="104" type="ans ..." maxLength="100"/>
	    <field no="105" type="ans ..." maxLength="999"/>
	    <field no="106" type="ans ..." maxLength="999"/>
	    <field no="107" type="ans ..." maxLength="999"/>
	    <field no="108" type="ans ..." maxLength="999"/>
	    <field no="109" type="ans ..." maxLength="999"/>
	    <field no="110" type="ans ..." maxLength="999"/>
	    <field no="111" type="ans ..." maxLength="999"/>
	    <field no="112" type="ans ..." maxLength="999"/>
	    <field no="113" type="ans ..." maxLength="999"/>
	    <field no="114" type="ans ..." maxLength="999"/>
	    <field no="115" type="ans ..." maxLength="999"/>
	    <field no="116" type="ans ..." maxLength="999"/>
	    <field no="117" type="ans ..." maxLength="999"/>
	    <field no="118" type="ans ..." maxLength="999"/>
	    <field no="119" type="ans ..." maxLength="999"/>
	    <field no="120" type="ans ..." maxLength="999"/>
	    <field no="121" type="ans ..." maxLength="999"/>
	    <field no="122" type="ans ..." maxLength="999"/>
	    <field no="123" type="ans ..." maxLength="999"/>
	    <field no="124" type="ans ..." maxLength="999"/>
	    <field no="125" type="ans ..." maxLength="999"/>
	    <field no="126" type="ans ..." maxLength="999"/>
	    <field no="127" type="ans ..." maxLength="999"/>
	    <field no="128" type="b" length="8"/>
	</message>
</nucleus8583>

=== jocnud/nucleus8583/nucleus8583-core/src/test/resources/META-INF/sub-message.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<nucleus8583 xmlns="http://www.nucleus8583.org/schema/nucleus8583"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.nucleus8583.org/schema/nucleus8583 
                                 http://www.nucleus8583.org/schema/nucleus8583.xsd">

    <import url="classpath:META-INF/nucleus8583/nucleus8583-types.xml" />
    
    <message name="sub1">
        <field no="1" type="bitmap" />
        <field no="2" type="ans .." />
    </message>
    
	<message name="sub-message">
		<field no="0" type="ans" length="4" alignment="none" />
		<field no="1" type="bitmap" />
		<field no="2" type="ans .." />
		<field no="3" type="ans" length="6" alignment="none" />
		<field no="4" type="ans" length="12" />
		<field no="5" type="ans" length="12" alignment="none" />
		<field no="6" type="ans" length="12" alignment="none" />
		<field no="7" type="ans" length="10" alignment="none" />
		<field no="8" type="ans" length="8" alignment="none" />
		<field no="9" type="ans" length="8" alignment="none" />
		<field no="10" type="ans" length="8" alignment="none" />
		<field no="11" type="ans" length="6" alignment="none" />
		<field no="12" type="ans" length="6" alignment="none" />
		<field no="13" type="ans" length="4" alignment="none" />
		<field no="14" type="ans" length="4" alignment="none" />
		<field no="15" type="ans" length="4" alignment="none" />
		<field no="16" type="ans" length="4" alignment="none" />
		<field no="17" type="ans" length="4" alignment="none" />
		<field no="18" type="ans" length="4" alignment="none" />
		<field no="19" type="ans" length="3" alignment="none" />
		<field no="20" type="ans" length="3" alignment="none" />
		<field no="21" type="ans" length="3" alignment="none" />
		<field no="22" type="ans" length="3" alignment="none" />
		<field no="23" type="ans" length="3" alignment="none" />
		<field no="24" type="ans" length="3" alignment="none" />
		<field no="25" type="ans" length="2" alignment="none" />
		<field no="26" type="ans" length="2" alignment="none" />
		<field no="27" type="ans" length="1" alignment="none" />
		<field no="28" type="ans" length="9" alignment="none" />
		<field no="29" type="ans" length="9" alignment="none" />
		<field no="30" type="ans" length="9" alignment="none" />
		<field no="31" type="ans" length="9" alignment="none" />
		<field no="32" type="ans .." />
		<field no="33" type="ans .." />
		<field no="34" type="ans .." />
		<field no="35" type="ans .." />
		<field no="36" type="ans ..." />
		<field no="37" type="ans" length="12" alignment="none" />
		<field no="38" type="ans" length="6" alignment="none" />
		<field no="39" type="ans" length="2" alignment="none" />
		<field no="40" type="ans" length="3" alignment="none" />
		<field no="41" type="ans" length="8" alignment="none" />
		<field no="42" type="ans" length="15" alignment="none" />
		<field no="43" type="ans" length="40" alignment="none" />
		<field no="44" type="ans .." />
		<field no="45" type="ans .." />
		<field no="46" type="ans ..." />
		<field no="47" type="ans ..." />
		<field no="48" type="ans ..." subMessage-ref="sub1" />
		<field no="49" type="ans" length="3" alignment="none" />
		<field no="50" type="ans" length="3" alignment="none" />
		<field no="51" type="ans" length="3" alignment="none" />
		<field no="52" type="ans" length="16" alignment="none" />
		<field no="53" type="ans" length="16" alignment="none" />
		<field no="54" type="ans ..." />
		<field no="55" type="ans ..." />
		<field no="56" type="ans ..." />
		<field no="57" type="ans ..." />
		<field no="58" type="ans ..." />
		<field no="59" type="ans ..." />
		<field no="60" type="ans ..." />
		<field no="61" type="ans ..." />
		<field no="62" type="ans ..." />
		<field no="63" type="ans ..." />
		<field no="64" type="b" length="16" />
		<field no="65" type="bitmap" />
		<field no="66" type="ans" length="1" alignment="none" />
		<field no="67" type="ans" length="2" alignment="none" />
		<field no="68" type="ans" length="3" alignment="none" />
		<field no="69" type="ans" length="3" alignment="none" />
		<field no="70" type="ans" length="3" alignment="none" />
		<field no="71" type="ans" length="4" alignment="none" />
		<field no="72" type="ans" length="4" alignment="none" />
		<field no="73" type="ans" length="6" alignment="none" />
		<field no="74" type="ans" length="10" alignment="none" />
		<field no="75" type="ans" length="10" alignment="none" />
		<field no="76" type="ans" length="10" alignment="none" />
		<field no="77" type="ans" length="10" alignment="none" />
		<field no="78" type="ans" length="10" alignment="none" />
		<field no="79" type="ans" length="10" alignment="none" />
		<field no="80" type="ans" length="10" alignment="none" />
		<field no="81" type="ans" length="10" alignment="none" />
		<field no="82" type="ans" length="12" alignment="none" />
		<field no="83" type="ans" length="12" alignment="none" />
		<field no="84" type="ans" length="12" alignment="none" />
		<field no="85" type="ans" length="12" alignment="none" />
		<field no="86" type="ans" length="16" alignment="none" />
		<field no="87" type="ans" length="16" alignment="none" />
		<field no="88" type="ans" length="16" alignment="none" />
		<field no="89" type="ans" length="16" alignment="none" />
		<field no="90" type="ans" length="26" alignment="none" />
		<field no="91" type="ans" length="1" alignment="none" />
		<field no="92" type="ans" length="2" alignment="none" />
		<field no="93" type="ans" length="6" alignment="none" />
		<field no="94" type="ans" length="7" alignment="none" />
		<field no="95" type="ans" length="42" alignment="none" />
		<field no="96" type="b" length="16" />
		<field no="97" type="ans" length="17" alignment="none" />
		<field no="98" type="ans" length="25" alignment="none" />
		<field no="99" type="ans .." />
		<field no="100" type="ans .." />
		<field no="101" type="ans .." />
		<field no="102" type="ans .." />
		<field no="103" type="ans .." />
		<field no="104" type="ans ..." />
		<field no="105" type="ans ..." />
		<field no="106" type="ans ..." />
		<field no="107" type="ans ..." />
		<field no="108" type="ans ..." />
		<field no="109" type="ans ..." />
		<field no="110" type="ans ..." />
		<field no="111" type="ans ..." />
		<field no="112" type="ans ..." />
		<field no="113" type="ans ..." />
		<field no="114" type="ans ..." />
		<field no="115" type="ans ..." />
		<field no="116" type="ans ..." />
		<field no="117" type="ans ..." />
		<field no="118" type="ans ..." />
		<field no="119" type="ans ..." />
		<field no="120" type="ans ..." />
		<field no="121" type="ans ..." />
		<field no="122" type="ans ..." />
		<field no="123" type="ans ..." />
		<field no="124" type="ans ..." />
		<field no="125" type="ans ..." />
		<field no="126" type="ans ..." />
		<field no="127" type="ans ..." />
		<field no="128" type="b" length="8" />
	</message>
</nucleus8583>
